<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDTNOjBG\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDTNOjBG/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDTNOjBG.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDTNOjBG\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDTNOjBG\appAppKernelProdContainer([
    'container.build_hash' => 'DTNOjBG',
    'container.build_id' => '5d0a2f32',
    'container.build_time' => 1778048557,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDTNOjBG');
