<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRcIn9t5\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRcIn9t5/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerRcIn9t5.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerRcIn9t5\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerRcIn9t5\appAppKernelProdContainer([
    'container.build_hash' => 'RcIn9t5',
    'container.build_id' => '303ca7a3',
    'container.build_time' => 1777992308,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRcIn9t5');
