<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFTzIkHU\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFTzIkHU/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFTzIkHU.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerFTzIkHU\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerFTzIkHU\appAppKernelProdContainer([
    'container.build_hash' => 'FTzIkHU',
    'container.build_id' => 'b0d23d7d',
    'container.build_time' => 1778076795,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFTzIkHU');
